#!/bin/bash

input="$1"
page="$2"
directory=$3

if test -f "$input"; then
    echo
else
    echo "file $input does not exist."
    exit 1
fi
base_name=`basename ${input}`
base_predix="${base_name%.*}"
parent_dir=`dirname "$input"`


output="${parent_dir}/${base_predix}_${page}.pdf"

if [ -z "$3" ]
then
  #empty
  echo
else
  output="${3}/${base_predix}_${page}.pdf"
fi

gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -dSAFER -dFirstPage=$page -dLastPage=$page  -sstdout=/dev/null -sOutputFile="${output}" "${input}"
#echo pdftk "${input}" cat "$page" "$output"
#pdftk "${input}" cat "$page" output "$output"
